server:
  port: 8080

spring:
  application:
    name: demo-app

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTLP_TRACING_ENPOINT}
    metrics:
      export:
        enabled: false