minimalPvc: &minimalPvc
  enabled: true
  type: pvc
  size: 2Gi

defaultPvc: &defaultPvc
  enabled: true
  type: pvc
  size: 5Gi

minimalResources: &minimalResources
  requests: { cpu: 25m, memory: 32Mi }
  limits: { cpu: 50m, memory: 64Mi }

defaultResources: &defaultResources
  requests: { cpu: 50m, memory: 64Mi }
  limits: { cpu: 100m, memory: 128Mi }

minimumResources: &minimumResources
  requests: { cpu: 100m, memory: 256Mi }
  limits: { cpu: 200m, memory: 512Mi }

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    resources: *minimumResources

grafana:
  resources: *minimumResources
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      url: http://loki-loki-distributed-gateway
      isDefault: false

    - name: Tempo
      uid: tempo
      type: tempo
      url: http://tempo-query-frontend:3200
      isDefault: false

prometheusOperator:
  resources: *defaultResources

kube-state-metrics:
  resources: *minimalResources

prometheus-node-exporter:
  resources: *minimalResources