minimalPvc: &minimalPvc
  enabled: true
  type: pvc
  size: 2Gi

defaultPvc: &defaultPvc
  enabled: true
  type: pvc
  size: 5Gi

minimalResources: &minimalResources
  requests: { cpu: 25m, memory: 32Mi }
  limits: { cpu: 50m, memory: 64Mi }

defaultResources: &defaultResources
  requests: { cpu: 50m, memory: 64Mi }
  limits: { cpu: 100m, memory: 128Mi }

minimumResources: &minimumResources
  requests: { cpu: 100m, memory: 256Mi }
  limits: { cpu: 200m, memory: 512Mi }

ingester:
  replicas: 1
  persistence: *minimalPvc
  resources: *minimalResources

distributor:
  replicas: 1
  resources: *minimalResources

querier:
  replicas: 1
  resources: *minimalResources

queryFrontend:
  replicas: 1
  resources: *minimalResources

gateway:
  replicas: 1
  resources: *minimalResources

compactor:
  replicas: 1
  resources: *minimalResources