alloy:
  configMap:
    create: false
    name: alloy-config
    key: config.alloy

  envFrom:
    - configMapRef:
        name: monitoring-endpoints

  extraPorts:
    - name: "otlphttp"
      port: 4318
      targetPort: 4318
    - name: "otlpgrpc"
      port: 4317
      targetPort: 4317
    - name: "loki"
      port: 3100
      targetPort: 3100

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
