minimalPvc: &minimalPvc
  enabled: true
  type: pvc
  size: 2Gi

defaultPvc: &defaultPvc
  enabled: true
  type: pvc
  size: 5Gi

minimalResources: &minimalResources
  requests: { cpu: 25m, memory: 32Mi }
  limits: { cpu: 50m, memory: 64Mi }

defaultResources: &defaultResources
  requests: { cpu: 50m, memory: 64Mi }
  limits: { cpu: 100m, memory: 128Mi }

minimumResources: &minimumResources
  requests: { cpu: 100m, memory: 256Mi }
  limits: { cpu: 200m, memory: 512Mi }

traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true

ingester:
  replicas: 1
  persistence: *minimalPvc
  resources: *minimalResources
  config:
    trace_idle_period: 30s
    replication_factor: 1

compactor:
  replicas: 1
  resources: *minimalResources
  config:
    block_retention: 2d

distributor:
  replicas: 1
  resources: *minimalResources

querier:
  replicas: 1
  resources: *minimalResources

queryFrontend:
  replicas: 1
  resources: *minimalResources

overrides:
  defaults:
    metrics_generator:
      processors:
        - span-metrics
        - service-graphs

metricsGenerator:
  enabled: true
  replica: 1
  resources: *minimalResources
  config:
    storage:
      remote_write:
        - name: prometheus
          send_exemplars: true
          url: http://prom-stack-kube-prometheus-prometheus:9090/api/v1/write