defaultPvc: &defaultPvc
  enabled: true
  type: pvc
  size: 2Gi

defaultResources: &defaultResources
  requests: { cpu: 20m, memory: 64Mi }
  limits: { cpu: 40m, memory: 128Mi }

ingester:
  replicas: 1
  persistence: *defaultPvc
  resources: *defaultResources
  config:
    trace_idle_period: 30s
compactor:
  replicas: 1
  resources: *defaultResources
  config:
    block_retention: 2d
distributor:
  replicas: 1
  resources: *defaultResources
querier:
  replicas: 1
  resources: *defaultResources
queryFrontend:
  replicas: 1
  resources: *defaultResources